debug: true
server:
  port: 8080
spring:
  config:
    import: classpath:secret.yml

  sql:
    init:
      platform: postgresql
      mode: always

  output:
    ansi:
      enabled: always

  datasource:
    url: ${database.url}
    username: ${database.username:Andreas}
    password: ${database.password:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

#openai:
#  model: gpt-3.5-turbo
#  api:
#    url: https://api.openai.com/v1/chat/completions
#    key: ${OPENAI_API_KEY}