INSERT INTO message (id, message) VALUES (1, 'Kubernetes is an open-source container orchestration platform.');
INSERT INTO message (id, message) VALUES (2, 'Kubernetes automates the deployment, scaling, and management of containerized applications.');
INSERT INTO message (id, message) VALUES (3, 'A Kubernetes cluster consists of a control plane and worker nodes.');
INSERT INTO message (id, message) VALUES (4, 'The control plane is responsible for managing the cluster’s overall state.');
INSERT INTO message (id, message) VALUES (5, 'A pod is the smallest deployable unit in Kubernetes.');
INSERT INTO message (id, message) VALUES (6, 'Pods in Kubernetes can contain one or more containers.');
INSERT INTO message (id, message) VALUES (7, 'The Kubernetes API server is the central management point of the cluster.');
INSERT INTO message (id, message) VALUES (8, 'Kubernetes uses Deployments to manage stateless applications.');
INSERT INTO message (id, message) VALUES (9, 'StatefulSets in Kubernetes manage stateful applications, like databases.');
INSERT INTO message (id, message) VALUES (10, 'Kubernetes uses ReplicaSets to ensure that a specified number of pod replicas are running.');
INSERT INTO message (id, message) VALUES (11, 'Kubernetes Services provide a stable endpoint to access a set of pods.');
INSERT INTO message (id, message) VALUES (12, 'A Namespace in Kubernetes is used to organize and isolate resources within a cluster.');
INSERT INTO message (id, message) VALUES (13, 'Kubernetes Ingress is used to manage external access to services, typically HTTP.');
INSERT INTO message (id, message) VALUES (14, 'Kubernetes ConfigMaps allow you to store non-sensitive configuration data.');
INSERT INTO message (id, message) VALUES (15, 'Kubernetes Secrets are used to store sensitive information like passwords and tokens.');
INSERT INTO message (id, message) VALUES (16, 'Kubernetes Horizontal Pod Autoscaler adjusts the number of pods based on CPU or memory usage.');
INSERT INTO message (id, message) VALUES (17, 'Kubernetes persistent volumes (PVs) provide storage resources that outlive pods.');
INSERT INTO message (id, message) VALUES (18, 'Kubernetes Helm is a package manager for deploying applications to Kubernetes.');
INSERT INTO message (id, message) VALUES (19, 'A Kubernetes Node is a worker machine that runs containers and supports pods.');
INSERT INTO message (id, message) VALUES (20, 'Kubernetes RBAC (Role-Based Access Control) helps secure your cluster by managing user permissions.');
