version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'messageDb'
    environment:
      - POSTGRES_USER=Andreas
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=messageDb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

