apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-api
  template:
    metadata:
      labels:
        app: message-api
    spec:
      containers:
        - name: message-api
          image: andreaslundmark/kubernetes-setup
          imagePullPolicy: Always
          ports:
            - containerPort: 8080